services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  T3\CliConfig\:
    resource: '../Classes/*'

  T3\CliConfig\Command\ConfigurationCommand:
    tags:
      - name: 'console.command'
        command: 'configuration:set'
